services:
  taskhive-api:
    build:
      context: .
      dockerfile: src/TaskHive.Api/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000/;https://+:5001/
      - ASPNETCORE_HTTP_PORT=5000
      - ASPNETCORE_HTTPS_PORT=5001
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetcore-devcert.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=DevCertPassword
      - DB_CONNECTION_STRING=${DB_CONNECTION_STRING}
    volumes:
      - /workspaces/taskhive/src/TaskHive.Api/aspnetcore-devcert.pfx:/https/aspnetcore-devcert.pfx:ro
    depends_on:
      - taskhive-db

  taskhive-db:
    image: "mcr.microsoft.com/mssql/server:2022-CU17-ubuntu-22.04"
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      MSSQL_PID: "Developer"
      ACCEPT_EULA: "Y"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - taskhive-db-data:/var/opt/mssql
    entrypoint: [ "/bin/bash", "-c", "/opt/mssql/bin/sqlservr & sleep 10 && /opt/mssql-tools18/bin/sqlcmd -S localhost -U SA -P ${MSSQL_SA_PASSWORD} -d master -i /docker-entrypoint-initdb.d/init.sql -v Password=\"${MSSQL_DEV_PASSWORD}\" -N o && tail -f /dev/null" ]

volumes:
  taskhive-db-data:
